steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sample-colyseus-service', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/sample-colyseus-service']

    # deploy api service
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'sample-colyseus-service',
          '--image', 'gcr.io/$PROJECT_ID/sample-colyseus-service',
          '--region', 'us-west1',
          '--platform', 'managed',
          '--allow-unauthenticated',
          '--env-vars-file', './.env.yaml'
          ]
